.TH PALM-SYNC-DAEMON 1
.SH NAME
palm-sync-daemon \- synchronize Palm with org-files
.SH SYNOPSIS
.B palm-sync-daemon
[\fBOPTION\fR]
.SH DESCRIPTION
.B palm-sync-daemon
is a daemon to synchronize Palm with given org-files.
.SH OPTIONS
.TP
.BR \-f ", " \-\-foreground
Run daemon in foreground.
.TP
.BR \-d ", " \-\-device =\fIDEVICE\fR
Palm PDA symbolic device where to connect. \fI/dev/ttyUSB1\fR by default.
.SH EXIT STATUS
.TP
.BR 0
Program exited normally,
.TP
.BR 1
Failed to parse commandline arguments,
.TP
.BR 2
Failed to setup
.BR atexit()
function,
.TP
.BR 3
Failed to daemonize.
.SH ENVIRONMENT
.TP
PALM_SYNC_NOTES_ORG
Path to OrgMode file with notes.
.TP
PALM_SYNC_TODO_ORG
Path to OrgMode file with TODO items and calendar records.
.SH AUTHOR
Written by Eugene Andrienko.
.SH REPORTING BUGS
Report bugs to <https://github.com/eugeneandrienko/palm-sync-daemon/issues>
